https://www.ambitionbox.com/list-of-companies?campaign=desktop_nav&page=1

In [3]:
import pandas as pd 
import numpy as np
import requests
from bs4 import BeautifulSoup

In [4]:
headers = {'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
webpage = requests.get('https://www.ambitionbox.com/list-of-companies?campaign=desktop_nav&page=2',headers = headers).text

In [5]:
soup=BeautifulSoup(webpage,'html.parser')

In [6]:
# H2 is the html tag that contains all the titles.

soup.find_all("h2")

[<h2 class="company-name bold-title-l" title="IndusInd Bank">
 									IndusInd Bank
 								</h2>,
 <h2 class="company-name bold-title-l" title="Mahindra &amp; Mahindra">
 									Mahindra &amp; Mahin...
 								</h2>,
 <h2 class="company-name bold-title-l" title="DXC Technology">
 									DXC Technology
 								</h2>,
 <h2 class="company-name bold-title-l" title="Infosys BPM ">
 									Infosys BPM
 								</h2>,
 <h2 class="company-name bold-title-l" title="IDFC FIRST Bank">
 									IDFC FIRST Bank
 								</h2>,
 <h2 class="company-name bold-title-l" title="Maruti Suzuki">
 									Maruti Suzuki
 								</h2>,
 <h2 class="company-name bold-title-l" title="Hinduja Global Solutions">
 									Hinduja Global S...
 								</h2>,
 <h2 class="company-name bold-title-l" title="Bajaj Finserv">
 									Bajaj Finserv
 								</h2>,
 <h2 class="company-name bold-title-l" title="HSBC Group">
 									HSBC Group
 								</h2>,
 <h2 class="company-name bold-title-l" title="Conneqt Business Solutions">
 									Conneqt Business...
 								</h2>,
 <h2 class="company-name bold-title-l" title="Ericsson">
 									Ericsson
 								</h2>,
 <h2 class="company-name bold-title-l" title="Mphasis">
 									Mphasis
 								</h2>,
 <h2 class="company-name bold-title-l" title="iEnergizer">
 									iEnergizer
 								</h2>,
 <h2 class="company-name bold-title-l" title="PwC">
 									PwC
 								</h2>,
 <h2 class="company-name bold-title-l" title="Startek">
 									Startek
 								</h2>,
 <h2 class="company-name bold-title-l" title="HDFC Life">
 									HDFC Life
 								</h2>,
 <h2 class="company-name bold-title-l" title="Yes Bank">
 									Yes Bank
 								</h2>,
 <h2 class="company-name bold-title-l" title="Dr. Reddy's">
 									Dr. Reddy's
 								</h2>,
 <h2 class="company-name bold-title-l" title="Asian Paints">
 									Asian Paints
 								</h2>,
 <h2 class="company-name bold-title-l" title="Cipla Pharmaceutical">
 									Cipla Pharmaceut...
 								</h2>,
 <h2 class="company-name bold-title-l" title="Sutherland Global Services">
 									Sutherland Globa...
 								</h2>,
 <h2 class="company-name bold-title-l" title="NTT DATA">
 									NTT DATA
 								</h2>,
 <h2 class="company-name bold-title-l" title="Jana Small Finance Bank">
 									Jana Small Finan...
 								</h2>,
 <h2 class="company-name bold-title-l" title="ICICI Prudential Life Insurance">
 									ICICI Prudential...
 								</h2>,
 <h2 class="company-name bold-title-l" title="EXL Service">
 									EXL Service
 								</h2>,
 <h2 class="company-name bold-title-l" title="Udaan">
 									Udaan
 								</h2>,
 <h2 class="company-name bold-title-l" title="HCL Group">
 									HCL Group
 								</h2>,
 <h2 class="company-name bold-title-l" title="Lupin">
 									Lupin
 								</h2>,
 <h2 class="company-name bold-title-l" title="KPMG">
 									KPMG
 								</h2>,
 <h2 class="company-name bold-title-l" title="UltraTech Cement">
 									UltraTech Cement
 								</h2>]

In [38]:
#strip is used to strip all the spaces before each and every title name. ex=(  amazon  ) will become (amazon  ).

for i in soup.find_all("h2"):
    print(i.text.strip())

IndusInd Bank
Mahindra & Mahin...
DXC Technology
Infosys BPM
IDFC FIRST Bank
Maruti Suzuki
Hinduja Global S...
Bajaj Finserv
HSBC Group
Conneqt Business...
Ericsson
Mphasis
iEnergizer
PwC
Startek
HDFC Life
Yes Bank
Dr. Reddy's
Asian Paints
Cipla Pharmaceut...
Sutherland Globa...
NTT DATA
Jana Small Finan...
ICICI Prudential...
Udaan
EXL Service
HCL Group
Lupin
KPMG
UltraTech Cement

In [39]:
for i in soup.find_all("p"):
    print(i.text.strip())

AmbitionBox
Discover Best Places to work in India
AmbitionBox




Discover best places to work
Compare & find best workplace
Bring your workplace to life
Highlight your company's perks
Read reviews for 6L+ companies
Rate your former or current company
Discover salaries for 6L+ companies
Calculate your take home salary
Check your market value
Help other jobseekers
Read interviews for 40K+ companies
Interviews questions for 1K+ colleges
Contribute your interview questions
Discover Best Places to Work!
Company reviews. Salaries. Interviews. Jobs.
About Company
8,63,789 unique
			companies found
Sort By:
Popular
3.8
Public
Gurgaon/Gurugram,Haryana + 615 more
29 years old
10k-50k Employees (India)
IndusInd Bank is a Mumbai based scheduled private bank founded in Mumbai in April 1994. This bank offers a wide range of banking as well as financial products and services to the customers and is headquartered in Mumbai, Maharashtra. The bank has over 745 branches with a total network of over 1635 operating ATMs. It has two representative offices outside India in London and Dubai respectively.
IndusInd Bank stands tall today as one of the reputed banking brands in the country. The bank has been continuously investing in various advertising & marketing programs to enhance the brand image & recall. In an endeavor to emerge as best-in-class brand, IndusInd Bank has made 'Responsive Innovation' as a central theme of its brand building program. The Bank has combined responsiveness with innovation to launch a wide range of banking products and services which are unique, convenient and very relevant to Indian consumer.
4.2
#1 Best Mega Company - 2022
Public
Mumbai,Maharashtra + 427 more
78 years old
1 Lakh+ Employees (India)
A federation of companies, bound by one purpose &ndash; to Rise. Inspired by this spirit, our legacy, and values, our goal to always positively impact our partners, stakeholders, communities, and the world at large, remains unshakeable. What began as a steel-trading venture seven decades ago, steadily turned into a global brand, spanning nations and industries. This is a story with an upward curve, narrating how an Indian company paved its way to become a global powerhouse. We have come a long way since 1945 and as we accelerate into the 21st century, we aim at achieving even more.
3.9
Public
Minato,Tokyo + 56 more
6 years old
10k-50k Employees (India)
We deliver the mission critical IT services that move the world.

DXC Technology is a Fortune 500 global IT services leader. Our more than 130,000 people in 70-plus countries are entrusted by our customers to deliver what matters most. We use the power of technology to deliver mission critical IT services across the Enterprise Technology Stack to drive business impact. DXC is an employer of choice with strong values, and fosters a culture of inclusion, belonging and corporate citizenship. We are DXC.

What we do
We deliver the IT services our customers need to modernize operations and drive innovation across their entire IT estate.

We provide services across the Enterprise Technology Stack for business process outsourcing, analytics and engineering, applications, security, cloud, IT outsourcing and modern workplace.

How we work
Every day, we earn our customers’ trust by delivering transformative technologies to ensure the success, safety and well-being of businesses and people worldwide.

We provide world-class IT services at scale from our Global Innovation and Delivery Centers in North America, South America, Europe, Asia and Australia. Our globally connected centers enable us to solve complex technology challenges and transform our customers’ businesses through our dedicated delivery workforce of more than 110,000 people. With globally distributed teams and rich engineering skills, DXC offers competitive solutions to address customers’ cost, regulatory, language and business continuity requirements.

We leverage the power of partnerships through our curated DXC ecosystem of technology leaders. By combining strengths and expertise globally, we create solutions and deliver greater outcomes for customers across the Enterprise Technology Stack.

Our values
Our values are the fabric of DXC. They bind us together regardless of where or how we work and position us to succeed on our transformation journey.

Join our team
We inspire and take care of our people. We work to create a culture of learning, diversity and inclusion and are dedicated to strong ethics and corporate citizenship. In each of the three regions where we work — Americas; Europe, Middle East and Africa; and Asia Pacific — we’re singularly focused on delivering excellence for our customers.

DXC is where brilliant people embrace change and seize opportunities to advance their careers and amplify customer success.
3.9
Bangalore/Bengaluru,Karnataka + 52 more
21 years old
10k-50k Employees (India)
Infosys BPM, the business process management subsidiary of Infosys (NYSE: INFY), provides end-to-end transformative services for its clients across the globe. The company’s integrated IT and BPM solutions approach enables it to unlock business value across industries and service lines, and address business challenges for its clients. Utilizing innovative business excellence frameworks, ongoing productivity improvements, process reengineering, automation, and cutting-edge technology platforms, Infosys BPM enables its clients to achieve their cost reduction objectives, improve process efficiencies, enhance effectiveness, and deliver superior customer experience.
Infosys BPM has 32 delivery centers in 16 countries spread across 5 continents, with 43,111 employees from 100+ nationalities, as of December 2019.
The company has been consistently ranked among the leading BPM companies globally and has received over 60 awards and recognitions in the last 5 years, from key industry bodies and associations like the Outsourcing Center, SSON, and GSA, among others. Infosys BPM also has very robust people practices, as substantiated by the various HR-specific awards it has won over the years. The company has consistently been ranked among the top employers of choice, on the basis of its industry-leading HR best practices. The company’s senior leaders contribute widely to industry forums as BPM strategists.
4.0
Public
Mumbai,Maharashtra + 481 more
5 years old
10k-50k Employees (India)
IDFC FIRST Bank was founded by the merger of IDFC Bank and Capital first in December 2018. IDFC FIRST Bank provides a range of financial solutions to individuals, small businesses, and corporates. The Bank offers savings and current accounts, NRI accounts, salary accounts, Demat accounts, fixed and recurring deposits, home and personal loans, small business loans, forex products, payment solutions, and wealth management services. IDFC FIRST Bank has a nationwide presence and operates in Retail Banking, Wholesale Banking, and other banking segments. Customers can choose where and how they want to bank: 599 branches across India with 727 ATMs, 25000+ employees, and growing. IDFC FIRST Bank has business correspondent centres across India with net banking services, mobile banking applications, and 24/7 toll-free Banker-on-Call service for our customers.
4.1
#3 Best Large Automobile Company - 2022
Public
New Delhi,Delhi + 386 more
40 years old
10k-50k Employees (India)
Cars are what Maruti Suzuki builds. Experiences are what it creates.

Experiences fuelled by innovations, forward thinking, and a commitment to bring the very best to Indian roads. From the day the iconic Maruti 800 was launched in 1983, the company has been spearheading a revolution of change. Turning an entire country’s need for driving, into its love for driving.

However, tastes and demands keep on evolving with each new generation of Indians. This has not been looked at by Maruti Suzuki as a challenge, but as an inspiration to go beyond traditional boundaries of car-making. Infusing design and technology is one such step it has taken to make its cars meet new age expectations smoothly.

Today, Maruti Suzuki has its eyes set firmly on the possibilities of tomorrow. And everybody is invited on this journey.
4.0
Public
Bangalore/Bengaluru,Karnataka + 84 more
23 years old
10k-50k Employees (India)
A global leader in optimizing the customer experience lifecycle, digital transformation, and business process management, HGS is helping its clients become more competitive every day. HGS combines automation, analytics, and artificial intelligence with deep domain expertise focusing on digital customer experiences, back-office processing, contact centers, and HRO solutions. Part of the multi-billion-dollar conglomerate Hinduja Group, HGS takes a &ldquo;globally local&rdquo; approach. HGS has over 21,600 employees across 38 delivery centers in six countries, making a difference to some of the world&rsquo;s leading brands across verticals. For the year ended March 31, 2022, HGS had revenues of Rs. 32,636.9 million (US$ 439 million). Visit https://hgs.cx to learn how HGS transforms customer experiences and builds businesses for the future.
4.0
#3 Best Large Financial Services Company - 2021
Public
Pune,Maharashtra + 759 more
16 years old
10k-50k Employees (India)
Bajaj Finserv was formed in April 2007 as a result of its demerger from Bajaj Auto Limited to further the Group’s interests in financial services. This demerger enabled Bajaj Finserv to independently run the core businesses of Lending, Protection and savings. Bajaj Finserv Limited is the holding company for the businesses dealing with financial services of the Bajaj Group. It serves millions of customers in the financial services space by providing solutions for asset acquisition through financing, asset protection through general insurance, family protection and income protection in the form of life and health insurance and retirement and savings solutions
4.1
Private
Pune,Maharashtra + 52 more
21 years old
10k-50k Employees (India)
HSBC, officially known as The Hongkong and Shanghai Banking Corporation Limited, is a wholly owned subsidiary of HSBC, the largest bank in Hong Kong, and operates branches and offices throughout the Asia Pacific region, and in other countries around the world
3.7
Private
Mumbai,Maharashtra + 177 more
21 years old
10k-50k Employees (India)
Established in 2004, Conneqt Business Solutions Ltd. (formerly Tata Business Support Services Ltd) headquartered in Hyderabad, is a subsidiary of Quess Corp (BSE: 539978, NSE: QUESS), India’s leading business services provider.  Throughout our journey, top industry analysts such as Gartner, Nelson Hall and Dun & Bradstreet have ranked us amongst the top Customer Lifecycle Management and Business Process Management service providers in India and the Middle East.

We are committed to provide world-class customer experience with our dedicated team of over 32,000+ employees located across 26 delivery centres. We’re constantly refining our technologies and developing ideas to better serve our 120 clients in 24 Indian and 12 International languages in over 600 + locations across PAN India through our unique ‘Feet on Street’ offering. We have created a customer-centric collaborative ecosystem of people, platforms, processes and partners to align strategically with your business goals. We help elevate your organization with the power of our in-house domain expertise, cutting-edge technology, and analytics.

Besides Customer Lifecycle Management and Business Process Management services, Conneqt also provides Finance and Accounting (FAO), HR Shared Services (HRSS) and Middle and Back Office Services. The company uses its innovative DiB (Digital-in a-Box) framework to help clients rapidly develop digital services that are market ready. Conneqt is also investing in automation and analytics capabilities and geographical expansion into US, Middle East and APAC.
4.3
#7 Best Large Company - 2022
Private
Stockholm,Stockholm County + 138 more
147 years old
10k-50k Employees (India)
Ericsson is one of the leading providers of Information and Communication Technology (ICT) to service providers. We enable the full value of connectivity by creating game-changing technology and services that are easy to use, adopt, and scale, making our customers successful in a fully connected world.
3.6
Public
Bangalore/Bengaluru,Karnataka + 40 more
25 years old
10k-50k Employees (India)
Mphasis applies next-generation technology to help enterprises transform businesses globally. Customer centricity is foundational to Mphasis and is reflected in Mphasis’ Front2Back™ Transformation approach.

Front2Back™ uses the exponential power of cloud and cognitive to provide hyper-personalized (C=X2C2TM=1) digital experience to clients and their end customers. Mphasis’ Service Transformation approach helps ‘shrink the core’ through the application of digital technologies across legacy environments within an enterprise, enabling businesses to stay ahead in a changing world.

Mphasis’ core reference architectures and tools, speed, and innovation with domain expertise and specialization are key to building strong relationships with marquee clients.
4.2
Private
Noida,Uttar Pradesh + 17 more
23 years old
10k-50k Employees (India)
A conglomerate of some of the most sought-after solutions in the digital landscape, we are a global provider of an array of tech solutions that can help you reimagine the scope of your business.

Keeping in mind the big picture, we thrive on digitally transforming businesses through a comprehensive suite of Customer Management and Custom Content Development Services, helping you to reap increased profits through cost-effective, value-rich customer contacts and transformation solutions.

Founded in the year 2000, we believe in business process excellence. So, it’s a no-brainer that, we believe in quality over quantity. Developing and transforming customer data that serves the entire customer lifecycle is our niche and we take pride in bringing you unparalleled expertise through our team of 17,000+ professionals across 9 delivery centers, worldwide. We focus primarily on Customer Experience (CX) which is why our staff and customer retention rates are among the highest in the industry.
3.7
Partnership
London,United Kingdom + 74 more
143 years old
10k-50k Employees (India)
Building trust in society and solving important problems. With offices in 152 countries and almost 328,000 people, we are among the leading professional service,s networks in the world. We help organizations and individuals create the value, they are looking for, by delivering quality assurance, Tax and Advisory services. Some facts about PwC: - In FY22, PwC firms provided services to 84% of the Global Fortune 500 companies. - 148,822 people joined PwC firms around the world in FY22. - For the year ending 30 June 2022, PwC&rsquo;s gross revenues were US$50.3 billion.
3.3
Public
Mumbai,Maharashtra + 53 more
6 years old
10k-50k Employees (India)
For more than 25 years we’ve held an organization-wide conviction, that it’s our job to be the front line promoting and protecting your brand. Some of the world’s most prominent industry leaders, from telecommunication giants to technology power houses entrust STARTEK to uphold their reputations and to safe-guard their hard-won customers.

We work around the clock, around the world, and with great determination to ensure every customer interaction is one that authentically matters. It’s on this front line, in the moments of direct, person-to-person engagement, where the battle for customer loyalty lives or dies, and why we take our responsibility so seriously.

Every one of our centers has a program dedicated to improving and supporting the communities they are a part of through direct involvement and volunteerism. While we know paying it forward feels great, it also just makes good business sense. We’ve seen first hand what third party studies reinforce all the time — that engaged employees who have a sense of belonging, also have less absenteeism, lower turnover and are more profitable.

In addition to taking care of the communities our sites are in, STARTEK prides itself in taking care of one another during times of hardship as well. In 2014, STARTEK launched WIN (Warriors In Need), a foundation intended to provide basic necessities and temporary relief to any STARTEK employee as result of disaster or extraordinary life events.

The program was conceived by employees, for employees, and is primarily funded by STARTEK employee contributions to help one another in times of great need. The program is in its infancy, but has already proven to be an essential resource for facing a critical crisis.
4.1
Public
Mumbai,Maharashtra + 457 more
1 years old
10k-50k Employees (India)
HDFC Life Insurance Company Limited (Formerly HDFC Standard Life Insurance Company Limited) ('HDFC Life' / ‘Company’) is a joint venture between HDFC Ltd., one of India’s leading housing finance institution and Standard Life Aberdeen, a global investment company.

Established in 2000, HDFC Life is a leading long-term life insurance solutions provider in India, offering a range of individual and group insurance solutions that meet various customer needs such as Protection, Pension, Savings, Investment and Health. As on March 31, 2019 the Company had 38 individual and 11 group products in its portfolio, along with 8 optional rider benefits, catering to a diverse range of customer needs.

HDFC Life continues to benefit from its presence across the country with 412 branches and additional distribution touchpoints through several partnerships.  The partnerships comprise 265 bancassurance partners including NBFCs (Non-Banking Financial Companies), MFIs (Micro Finance Institutions), SFBs (Small Finance Banks), etc. and 39 partnerships within non-traditional ecosystems. The Company is also strengthened by a strong base of financial consultants.

In Fiscal 2012, The Company established a wholly-owned subsidiary, HDFC Pension Management Company Ltd., to operate its pension fund business under the National Pension Scheme (NPS). And in Fiscal 2016, the Company established its first international wholly-owned subsidiary in the UAE, HDFC International Life and Re Company Ltd., to operate its reinsurance business
3.9
#2 Best Large Banking Company - 2021
Public
Mumbai,Maharashtra + 399 more
19 years old
10k-50k Employees (India)
YES BANK, India’s fourth largest private sector bank is a high quality, customer centric and service driven Bank. Since inception in 2004, YES BANK has grown into a ‘Full Service Commercial Bank’ providing a complete range of products, services and technology driven digital offerings, catering to corporate, MSME & retail customers. YES BANK operates its Investment banking, Merchant banking & Brokerage businesses through YES SECURITIES and its Mutual Fund business through YES Asset Management (India) Limited, both wholly owned subsidiaries of the Bank. Headquartered in Mumbai, it has a pan-India presence across all 28 states and 9 Union Territories in India including an IBU at GIFT City, and a Representative Office in Abu Dhabi.
4.2
#24 Best Large Company - 2022
Public
Hyderabad/Secunderabad,Telangana + 145 more
39 years old
10k-50k Employees (India)

In [40]:
#Ratings.
soup.find_all("p",class_="rating")

[<p class="rating badge-large rating-35"><i class="icon icon-star"></i>
 									3.8
 								</p>,
 <p class="rating badge-large rating-4"><i class="icon icon-star"></i>
 									4.2
 								</p>,
 <p class="rating badge-large rating-35"><i class="icon icon-star"></i>
 									3.9
 								</p>,
 <p class="rating badge-large rating-35"><i class="icon icon-star"></i>
 									3.9
 								</p>,
 <p class="rating badge-large rating-4"><i class="icon icon-star"></i>
 									4.0
 								</p>,
 <p class="rating badge-large rating-4"><i class="icon icon-star"></i>
 									4.1
 								</p>,
 <p class="rating badge-large rating-4"><i class="icon icon-star"></i>
 									4.0
 								</p>,
 <p class="rating badge-large rating-4"><i class="icon icon-star"></i>
 									4.0
 								</p>,
 <p class="rating badge-large rating-4"><i class="icon icon-star"></i>
 									4.1
 								</p>,
 <p class="rating badge-large rating-35"><i class="icon icon-star"></i>
 									3.7
 								</p>,
 <p class="rating badge-large rating-4"><i class="icon icon-star"></i>
 									4.3
 								</p>,
 <p class="rating badge-large rating-35"><i class="icon icon-star"></i>
 									3.6
 								</p>,
 <p class="rating badge-large rating-4"><i class="icon icon-star"></i>
 									4.2
 								</p>,
 <p class="rating badge-large rating-35"><i class="icon icon-star"></i>
 									3.7
 								</p>,
 <p class="rating badge-large rating-3"><i class="icon icon-star"></i>
 									3.3
 								</p>,
 <p class="rating badge-large rating-4"><i class="icon icon-star"></i>
 									4.1
 								</p>,
 <p class="rating badge-large rating-35"><i class="icon icon-star"></i>
 									3.9
 								</p>,
 <p class="rating badge-large rating-4"><i class="icon icon-star"></i>
 									4.2
 								</p>,
 <p class="rating badge-large rating-4"><i class="icon icon-star"></i>
 									4.2
 								</p>,
 <p class="rating badge-large rating-4"><i class="icon icon-star"></i>
 									4.1
 								</p>,
 <p class="rating badge-large rating-35"><i class="icon icon-star"></i>
 									3.8
 								</p>,
 <p class="rating badge-large rating-4"><i class="icon icon-star"></i>
 									4.0
 								</p>,
 <p class="rating badge-large rating-35"><i class="icon icon-star"></i>
 									3.8
 								</p>,
 <p class="rating badge-large rating-4"><i class="icon icon-star"></i>
 									4.1
 								</p>,
 <p class="rating badge-large rating-4"><i class="icon icon-star"></i>
 									4.0
 								</p>,
 <p class="rating badge-large rating-35"><i class="icon icon-star"></i>
 									3.9
 								</p>,
 <p class="rating badge-large rating-35"><i class="icon icon-star"></i>
 									3.8
 								</p>,
 <p class="rating badge-large rating-4"><i class="icon icon-star"></i>
 									4.1
 								</p>,
 <p class="rating badge-large rating-35"><i class="icon icon-star"></i>
 									3.7
 								</p>,
 <p class="rating badge-large rating-4"><i class="icon icon-star"></i>
 									4.2
 								</p>]

In [41]:
# Review counts.
soup.find_all("a",class_="review-count")

[<a class="review-count sbold-Labels" href="https://www.ambitionbox.com/reviews/indusind-bank-reviews">
 									(7.7k Reviews)
 								</a>,
 <a class="review-count sbold-Labels" href="https://www.ambitionbox.com/reviews/mahindra-and-mahindra-reviews">
 									(7.6k Reviews)
 								</a>,
 <a class="review-count sbold-Labels" href="https://www.ambitionbox.com/reviews/dxc-technology-reviews">
 									(7k Reviews)
 								</a>,
 <a class="review-count sbold-Labels" href="https://www.ambitionbox.com/reviews/infosys-bpm-reviews">
 									(6.9k Reviews)
 								</a>,
 <a class="review-count sbold-Labels" href="https://www.ambitionbox.com/reviews/idfc-bank-reviews">
 									(6.5k Reviews)
 								</a>,
 <a class="review-count sbold-Labels" href="https://www.ambitionbox.com/reviews/maruti-suzuki-reviews">
 									(6.5k Reviews)
 								</a>,
 <a class="review-count sbold-Labels" href="https://www.ambitionbox.com/reviews/hinduja-global-solutions-reviews">
 									(6.2k Reviews)
 								</a>,
 <a class="review-count sbold-Labels" href="https://www.ambitionbox.com/reviews/bajaj-finserv-reviews">
 									(6.1k Reviews)
 								</a>,
 <a class="review-count sbold-Labels" href="https://www.ambitionbox.com/reviews/hsbc-reviews">
 									(6.1k Reviews)
 								</a>,
 <a class="review-count sbold-Labels" href="https://www.ambitionbox.com/reviews/qconneqt-reviews">
 									(6k Reviews)
 								</a>,
 <a class="review-count sbold-Labels" href="https://www.ambitionbox.com/reviews/ericsson-reviews">
 									(5.8k Reviews)
 								</a>,
 <a class="review-count sbold-Labels" href="https://www.ambitionbox.com/reviews/mphasis-reviews">
 									(5.7k Reviews)
 								</a>,
 <a class="review-count sbold-Labels" href="https://www.ambitionbox.com/reviews/ienergizer-reviews">
 									(5.6k Reviews)
 								</a>,
 <a class="review-count sbold-Labels" href="https://www.ambitionbox.com/reviews/pwc-reviews">
 									(5.5k Reviews)
 								</a>,
 <a class="review-count sbold-Labels" href="https://www.ambitionbox.com/reviews/startek-reviews">
 									(5.4k Reviews)
 								</a>,
 <a class="review-count sbold-Labels" href="https://www.ambitionbox.com/reviews/hdfc-life-reviews">
 									(5.4k Reviews)
 								</a>,
 <a class="review-count sbold-Labels" href="https://www.ambitionbox.com/reviews/yes-bank-reviews">
 									(5.3k Reviews)
 								</a>,
 <a class="review-count sbold-Labels" href="https://www.ambitionbox.com/reviews/dr-dot-reddys-reviews">
 									(5.3k Reviews)
 								</a>,
 <a class="review-count sbold-Labels" href="https://www.ambitionbox.com/reviews/asian-paints-reviews">
 									(5.3k Reviews)
 								</a>,
 <a class="review-count sbold-Labels" href="https://www.ambitionbox.com/reviews/cipla-pharmaceutical-ltd-reviews">
 									(5.2k Reviews)
 								</a>,
 <a class="review-count sbold-Labels" href="https://www.ambitionbox.com/reviews/sutherland-global-services-reviews">
 									(5.2k Reviews)
 								</a>,
 <a class="review-count sbold-Labels" href="https://www.ambitionbox.com/reviews/ntt-data-reviews">
 									(5k Reviews)
 								</a>,
 <a class="review-count sbold-Labels" href="https://www.ambitionbox.com/reviews/jana-small-finance-bank-reviews">
 									(4.9k Reviews)
 								</a>,
 <a class="review-count sbold-Labels" href="https://www.ambitionbox.com/reviews/icici-prudential-life-insurance-reviews">
 									(4.9k Reviews)
 								</a>,
 <a class="review-count sbold-Labels" href="https://www.ambitionbox.com/reviews/udaan-reviews">
 									(4.8k Reviews)
 								</a>,
 <a class="review-count sbold-Labels" href="https://www.ambitionbox.com/reviews/exl-service-reviews">
 									(4.8k Reviews)
 								</a>,
 <a class="review-count sbold-Labels" href="https://www.ambitionbox.com/reviews/hcl-reviews">
 									(4.8k Reviews)
 								</a>,
 <a class="review-count sbold-Labels" href="https://www.ambitionbox.com/reviews/lupin-reviews">
 									(4.8k Reviews)
 								</a>,
 <a class="review-count sbold-Labels" href="https://www.ambitionbox.com/reviews/kpmg-reviews">
 									(4.8k Reviews)
 								</a>,
 <a class="review-count sbold-Labels" href="https://www.ambitionbox.com/reviews/ultratech-cement-reviews">
 									(4.7k Reviews)
 								</a>]

##### Above process is tedious so we will try to fetch all the data for a particular company and then move to the next company and so on.

In [45]:
company =soup.find_all("div",class_ = 'company-content-wrapper')

In [50]:
company[0]

<div class="company-content-wrapper"><div class="company-content"><div class="company-logo"><img alt="IndusInd Bank logo" class="lazy" data-src="https://static.ambitionbox.com/assets/v2/images/rs:fit:200:200:false:false/bG9jYWw6Ly8vbG9nb3Mvb3JpZ2luYWxzL2luZHVzaW5kLWJhbmsuanBn.webp" height="100" onerror="this.onerror=null;this.src='/static/icons/company-placeholder.svg';" src="https://static.ambitionbox.com/static/icons/company-placeholder.svg" width="100"/></div> <div class="company-info-wrapper"><div class="company-info"><div class="left"><a href="/overview/indusind-bank-overview"><h2 class="company-name bold-title-l" title="IndusInd Bank">
									IndusInd Bank
								</h2></a> <div class="rating-wrapper"><p class="rating badge-large rating-35"><i class="icon icon-star"></i>
									3.8
								</p> <a class="review-count sbold-Labels" href="https://www.ambitionbox.com/reviews/indusind-bank-reviews">
									(7.7k Reviews)
								</a></div></div> <button class="ab_btn follow-btn invert round"><span class="ctas-btn-medium">Follow</span></button></div> <!-- --> <div class="company-basic-info"><p class="infoEntity sbold-list-header"><i class="icon-domain"></i>
							Public
						</p> <p class="infoEntity sbold-list-header"><i class="icon-pin-drop"></i>
							Gurgaon/Gurugram,Haryana + 615 more
						</p> <p class="infoEntity sbold-list-header"><i class="icon-access-time"></i>
							29 years old
						</p> <p class="infoEntity sbold-list-header"><i class="icon-supervisor-account"></i>
							10k-50k Employees (India)
						</p></div> <ul class="chips-block"><li><a class="ab_chip body-medium" data-filter-name="chips_Company-Tags_financial-services" href="/financial-services-companies-in-india" title="Financial Services companies in India">
								Financial Services
							</a></li><li><a class="ab_chip body-medium" data-filter-name="chips_Company-Tags_banking" href="/banking-companies-in-india" title="Banking companies in India">
								Banking
							</a></li><li><a class="ab_chip body-medium" data-filter-name="chips_Company-Tags_forbesglobal2000" href="/forbesglobal2000-companies-in-india" title="Forbes Global 2000 companies in India">
								Forbes Global 2000
							</a></li><li><a class="ab_chip body-medium" data-filter-name="chips_Company-Tags_fortune500" href="/fortune500-companies-in-india" title="Fortune India 500 companies in India">
								Fortune India 500
							</a></li><li><a class="ab_chip body-medium" data-filter-name="chips_Company-Tags_public" href="/public-companies-in-india" title="Public companies in India">
								Public
							</a></li><li><a class="ab_chip body-medium" data-filter-name="chips_Company-Tags_gurgaon" href="/companies-in-gurgaon" title="Companies in Gurgaon/Gurugram,Haryana">
								Gurgaon/Gurugram,Haryana
							</a></li></ul></div></div> <!-- --> <p class="description body-small" itemprop="description">
					IndusInd Bank is a Mumbai based scheduled private bank founded in Mumbai in April 1994. This bank offers a wide range of banking as well as financial products and services to the customers and is headquartered in Mumbai, Maharashtra. The bank has over 745 branches with a total network of over 1635 operating ATMs. It has two representative offices outside India in London and Dubai respectively.
IndusInd Bank stands tall today as one of the reputed banking brands in the country. The bank has been continuously investing in various advertising &amp; marketing programs to enhance the brand image &amp; recall. In an endeavor to emerge as best-in-class brand, IndusInd Bank has made 'Responsive Innovation' as a central theme of its brand building program. The Bank has combined responsiveness with innovation to launch a wide range of banking products and services which are unique, convenient and very relevant to Indian consumer.
				</p></div>

In [46]:
len(company)

30

In [92]:
name=[]
rating=[]
reviews=[]
ctype=[]
hq=[]
how_old=[]
no_of_employee=[]

for i in company:
    
    name.append(i.find("h2").text.strip())
    rating.append(i.find("p",class_="rating").text.strip())
    reviews.append(i.find("a",class_="review-count").text.strip())
    info_entities = i.find_all('p', class_='infoEntity')
    
    if len(info_entities) >= 4:
        ctype.append(info_entities[0].text.strip())
        hq.append(info_entities[1].text.strip())
        how_old.append(info_entities[2].text.strip())
        no_of_employee.append(info_entities[3].text.strip())
    else:
        ctype.append('')
        hq.append('')
        how_old.append('')
        no_of_employee.append('')
    
    
    
df = pd.DataFrame({"name":name,
                  "rating":rating,
                  "reviews":reviews,
                  'company_type':ctype,
                  'Head_Quarters':hq,
                  'Company_Age':how_old,
                  'No_of_Employee':no_of_employee,})

In [105]:
df

,name,rating,reviews,company_type,Head_Quarters,Company_Age,No_of_Employee
0,IndusInd Bank,3.8,(7.7k Reviews),Public,"Gurgaon/Gurugram,Haryana + 615 more",29 years old,10k-50k Employees (India)
1,Mahindra & Mahin...,4.2,(7.6k Reviews),Public,"Mumbai,Maharashtra + 427 more",78 years old,1 Lakh+ Employees (India)
2,DXC Technology,3.9,(7k Reviews),Public,"Minato,Tokyo + 56 more",6 years old,10k-50k Employees (India)
3,Infosys BPM,3.9,(6.9k Reviews),,,,
4,IDFC FIRST Bank,4.0,(6.5k Reviews),Public,"Mumbai,Maharashtra + 481 more",5 years old,10k-50k Employees (India)
5,Maruti Suzuki,4.1,(6.5k Reviews),Public,"New Delhi,Delhi + 386 more",40 years old,10k-50k Employees (India)
6,Hinduja Global S...,4.0,(6.2k Reviews),Public,"Bangalore/Bengaluru,Karnataka + 84 more",23 years old,10k-50k Employees (India)
7,Bajaj Finserv,4.0,(6.1k Reviews),Public,"Pune,Maharashtra + 759 more",16 years old,10k-50k Employees (India)
8,HSBC Group,4.1,(6.1k Reviews),Private,"Pune,Maharashtra + 52 more",21 years old,10k-50k Employees (India)
9,Conneqt Business...,3.7,(6k Reviews),Private,"Mumbai,Maharashtra + 177 more",21 years old,10k-50k Employees (India)
10,Ericsson,4.3,(5.8k Reviews),Private,"Stockholm,Stockholm County + 138 more",147 years old,10k-50k Employees (India)
11,Mphasis,3.6,(5.7k Reviews),Public,"Bangalore/Bengaluru,Karnataka + 40 more",25 years old,10k-50k Employees (India)
12,iEnergizer,4.2,(5.6k Reviews),Private,"Noida,Uttar Pradesh + 17 more",23 years old,10k-50k Employees (India)
13,PwC,3.7,(5.5k Reviews),Partnership,"London,United Kingdom + 74 more",143 years old,10k-50k Employees (India)
14,Startek,3.3,(5.4k Reviews),Public,"Mumbai,Maharashtra + 53 more",6 years old,10k-50k Employees (India)
15,HDFC Life,4.1,(5.4k Reviews),Public,"Mumbai,Maharashtra + 457 more",1 years old,10k-50k Employees (India)
16,Yes Bank,3.9,(5.3k Reviews),Public,"Mumbai,Maharashtra + 399 more",19 years old,10k-50k Employees (India)
17,Dr. Reddy's,4.2,(5.3k Reviews),Public,"Hyderabad/Secunderabad,Telangana + 145 more",39 years old,10k-50k Employees (India)
18,Asian Paints,4.2,(5.3k Reviews),Public,"Mumbai,Maharashtra + 371 more",81 years old,10k-50k Employees (India)
19,Cipla Pharmaceut...,4.1,(5.2k Reviews),Public,"Mumbai,Maharashtra + 196 more",88 years old,10k-50k Employees (India)
20,Sutherland Globa...,3.8,(5.2k Reviews),Private,"Pittsford,New York + 43 more",37 years old,10k-50k Employees (India)
21,NTT DATA,4.0,(5k Reviews),Private,"Chiyoda City,Tokyo + 45 more",35 years old,10k-50k Employees (India)
22,Jana Small Finan...,3.8,(4.9k Reviews),Public,"Bangalore/Bengaluru,Karnataka + 323 more",17 years old,10k-50k Employees (India)
23,ICICI Prudential...,4.1,(4.9k Reviews),Public,"Mumbai,Maharashtra + 417 more",23 years old,10k-50k Employees (India)
24,Udaan,4.0,(4.8k Reviews),Private,"Bangalore,Karnataka + 326 more",7 years old,1k-5k Employees (India)
25,EXL Service,3.9,(4.8k Reviews),Private,"New York City,New York + 35 more",24 years old,10k-50k Employees (India)
26,HCL Group,3.8,(4.8k Reviews),,,,
27,Lupin,4.1,(4.8k Reviews),Public,"Mumbai,Maharashtra + 141 more",55 years old,10k-50k Employees (India)
28,KPMG,3.7,(4.8k Reviews),Partnership,Bengaluru/Bangalore + 66 more,36 years old,10k-50k Employees (India)
29,UltraTech Cement,4.2,(4.7k Reviews),Public,"Mumbai,Maharashtra + 383 more",40 years old,10k-50k Employees (India)

### Creating dataframe for all pages

In [212]:
final=pd.DataFrame()
for j in range(1,2000):
    
    url = "https://www.ambitionbox.com/list-of-companies?page={}".format(j)
    headers = {'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
    webpage=requests.get(url, headers=headers).text
    
    soup=BeautifulSoup(webpage,'html.parser')
    company=soup.find_all('div',class_='company-content-wrapper')
    
    
    name = []
    rating = []
    reviews = []
    ctype = []
    hq = []
    how_old = []
    no_of_employee = []
    
    for i in company:

        try:
            name.append(i.find('h2').text.strip())
        except:
            name.append(np.nan)

        try:
            rating.append(i.find('p',class_='rating').text.strip())
        except:
            rating.append(np.nan)
   
        try:
            reviews.append(i.find('a' , class_='review-count').text.strip())
            
        except:
            reviews.append(np.nan)

        try:

            ctype.append(i.find_all('p',class_='infoEntity')[0].text.strip())
        except:
            ctype.append(np.nan)
        try:

            hq.append(i.find_all('p',class_='infoEntity')[1].text.strip())
        except:
            hq.append(np.nan)
    
        try:

            how_old.append(i.find_all('p',class_='infoEntity')[2].text.strip())
        except:
            how_old.append(np.nan)
        try:
            no_of_employee.append(i.find_all('p',class_='infoEntity')[3].text.strip())
        except:
            no_of_employee.append(np.nan)
    

    df=pd.DataFrame({'name':name,
       'rating':rating,
       'reviews':reviews,
       'company_type':ctype,
       'Head_Quarters':hq,
       'Company_Age':how_old,
       'No_of_Employee':no_of_employee,
        })
  
    final=final.append(df,ignore_index=True)

C:\Users\rohanpc\AppData\Local\Temp\ipykernel_24052\4234660837.py:69: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final=final.append(df,ignore_index=True)

In [213]:
final

,name,rating,reviews,company_type,Head_Quarters,Company_Age,No_of_Employee
0,TCS,3.8,(60.2k Reviews),Public,"Mumbai,Maharashtra + 278 more",55 years old,1 Lakh+ Employees (India)
1,Accenture,4.1,(38.5k Reviews),Public,Dublin + 139 more,34 years old,1 Lakh+ Employees (India)
2,Cognizant,3.9,(35k Reviews),Private,Teaneck. New Jersey. + 109 more,29 years old,1 Lakh+ Employees (India)
3,ICICI Bank,4.0,(28.6k Reviews),Public,"Mumbai,Maharashtra + 1163 more",29 years old,1 Lakh+ Employees (India)
4,Wipro,3.9,(28.5k Reviews),Public,"Bangalore/Bengaluru,Karnataka + 235 more",78 years old,1 Lakh+ Employees (India)
...,...,...,...,...,...,...,...
9984,Skylark Group,3.4,(60 Reviews),Safidon + 13 more,38 years old,501-1k Employees (Global),NaN
9985,OPK e Services,3.8,(60 Reviews),Gurgaon + 1 more,17 years old,51-200 Employees (India),NaN
9986,Volansys Technol...,3.9,(60 Reviews),Private,"Santa Clara,California",15 years old,201-500 Employees (India)
9987,Symbiosys Techno...,3.6,(60 Reviews),Private,"Visakhapatnam/Vizag,Andhra Pradesh + 3 more",22 years old,51-200 Employees (India)
9988,Royal Care Super...,4.4,(60 Reviews),Coimbatore + 2 more,8 years old,201-500 Employees (India),NaN

In [211]:
duplicate_values = final.duplicated('name')
print(duplicate_values)

0       False
1       False
2       False
3       False
4       False
        ...
9984    False
9985    False
9986    False
9987    False
9988    False
Length: 9989, dtype: bool

In [214]:
final.to_csv('output.csv', index=False)

In [215]:
final.to_excel('output.xlsx', index=False)